### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [nmcc1212/shades-of-purple-windows-terminal#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by nmcc1212** [comment]
Hey! only just seen this, added an MIT license. Would be great to see it on your list!
